### ISSUE TITLE
length error when doing `y_'x` on a matrix

### ISSUE THREAD

**Issue by vbmithr** [cmh25/gk#1]
```k  
  x:6 3#!18
  y:2
  y_x
(6 7 8
 9 10 11
 12 13 14
 15 16 17)
  y_'x
length error
y_'x
 ^
>  
```

**Comment by ghost** [comment]
I am still studying parser to see how each-prior is being parsed so have no explanation but it works as expected for explicit lambda. Also train pierces which is cool.

```
  {2_x}'x
(,2
 ,5
 ,8
 ,11
 ,14
 ,17)

  (y_)'x
type error
x:6 3#!18
^
>  \
  (y_)x
(,2
 ,5
 ,8
 ,11
 ,14
 ,17)
```

**Comment by cmh25** [comment]
@vbmithr, thanks for bringing this up.
@kafka64 , thanks for those examples.

The only form of `x f' y`  that gk currently supports is for the slide adverb, which is a generalization of each-prior (see README.md), the case of `-1 f' y` being the equivalent of k3 each-prior.
```
  -1 ,'"asdf"
("sa"
 "ds"
 "fd")
```

The k3 style each you're expecting is still available with square brackets.
```
  x:6 3#!18
  y:2
  _'[y;x]
(,2
 ,5
 ,8
 ,11
 ,14
 ,17)
```
Also, note that each-right is preferred for this case.
```
  y_/x
(,2
 ,5
 ,8
 ,11
 ,14
 ,17)
```

The really important feature of k3 style each is the conformance. Which is why gk supports it with the square brackets.
```
  x:("as";"df")
  y:"gh"
  ,'[x;y]
("asg"
 "dfh")
```

I have several discussions going on related to slide and each. I'm leaning toward making slide a named builtin and bringing back k3 style each. But I'm also waiting to see how this works in k9.

**Comment by cmh25** [comment]
@vbmithr fyi, just pushed changes to bring back the normal each we're all used to. For example, this works like you originally expected it to now.
```
  x:6 3#!18
  y:2
  y_'x
(,2
 ,5
 ,8
 ,11
 ,14
 ,17)
```

I believe most people will expect `x f' y` to work like it did in k3, and the slide adverb hasn't caught on very well. slide is too complicated and each just seems too valued to let go.

slide is still implemented, but as triadic `_` (see updated README.md) . For example:
```
  _[-1;,;"asdf"]
("sa"
 "ds"
 "fd")
```

The special case of slide that is equivalent to eachprior is also available as a builtin.
```
  ep[,;"asdf"]
("sa"
 "ds"
 "fd")
```
